name: Clean Up

env:
  RESOURCE_GROUP: 'RG'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checing Out Code
      uses: actions/checkout@v2
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Remove all resources
      run: az group delete --name ${{ env.RESOURCE_GROUP }} --yes
